# Generated by Django 4.2.11 on 2024-07-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_reply_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='body',
            field=models.TextField(default='This is a null value'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thread',
            name='body',
            field=models.TextField(default='This is a null value'),
            preserve_default=False,
        ),
    ]
